### ISSUE TITLE
deepFM中utilities的one_hot_representation方法返回的index截取，我认为存在bug

### ISSUE THREAD

**Issue by mymynew** [Johnson0722/CTR_Prediction#2]
https://github.com/Johnson0722/CTR_Prediction/blob/ec4de3d2654c5d808ff633d9a10cdd04d636db1e/Deep_FM/utilities.py#L26
idx[:21]按逻辑是想返回的下标中排除click项的值吧？而for field in fields_dict循环的最后一项，不一定是click。这会导致排除的是其他特征项的index，而click项还保留在当中。然后，dnn做embedding会下标越界…… 是吧？

**Comment by Johnson0722** [comment]
...我在check下

**Comment by land1725** [comment]
@mymynew 感谢您的提醒，真是一语惊醒梦中人，我调试了一天了，也没找到问题所在，您一句话，解决了

def one_hot_representation(sample, fields_dict, array_length):
    """
    One hot presentation for every sample data
    :param fields_dict: fields value to array index
    :param sample: sample data, type of pd.series
    :param array_length: length of one-hot representation
    :return: one-hot representation, type of np.array
    """
    array = np.zeros([array_length])
    idx = []
    for field in fields_dict:
        # get index of array
        if field == 'hour':
            field_value = int(str(sample[field])[-2:])
        else:
            field_value = sample[field]
        ind = fields_dict[field][field_value]
        array[ind] = 1
        if field!='click':
            idx.append(ind)
    return array,idx

**Comment by sunjiaxin111** [comment]
确实有这个bug

**Comment by DenceChen** [comment]
DeepFM中的y_embedding_input输入为什么是v，v是训练参数，应该是self.x?

**Comment by DenceChen** [comment]
在FFM代码中，tf.reduce_sum(tf.multiply(v[i,self.feature2field[i]], v[j,self.feature2field[j]])),论文中是v_(i,fj)和v_(j,fi)的内积，但是代码里是v_(i,fi)和v_(j,fj)的内积，请问这怎么理解，谢谢。

**Comment by DenceChen** [comment]
@Johnson0722 期待解答下我疑惑，感谢？
